// English interface strings.
//
// Every rendered string comes from a table; see zh.ts for the contract. The English table is a
// translation, never a second source of truth: the key set, placeholders and value shapes are
// asserted equal to the Chinese table by `tests/panel-strings.mjs`.

/** @type {import('./types.js').Strings} */
export const en = {
  // Title band and status banner
  appTitle: 'teamsmith pulse',
  patrolLabel: 'patrol',
  patrolSeconds: 'patrol {n}s',
  standbyLabel: 'standby',
  standbyOn: 'standby on (reason: {reason})',
  standbyOff: 'standby off',
  standbyDash: 'standby —',
  pmLabel: 'PM',
  pmDeliveryWarning: 'delivery degraded: {reason} → notifications fall back to the paste path (restart the process to load the extension)',
  pendingLabel: 'pending',
  pendingNone: 'none',
  outboxLabel: 'deferred',
  outboxHeldSuffix: ' (held {n})',
  capacityLabel: 'capacity',
  capacityRam: 'RAM {mb}',
  capacitySwap: 'swap {mb}',
  capacityAgents: '{n} more agents fit',
  dash: '—',

  // Project progress
  progressLabel: 'progress',
  progressTasks: 'tasks {parts}',
  taskTodo: 'todo',
  taskWip: 'wip',
  taskReview: 'review',
  taskBlocked: 'blocked',
  taskDone: 'done',
  taskDropped: 'dropped',
  progressChanges: 'changes {n}',
  progressSpecs: 'specs {specs} · {reqs} requirements',
  progressDecisions: 'decisions {n}',
  countPair: '{label} {n}',

  // Recent deliveries
  deliveriesLabel: 'recent deliveries',
  deliveryLine: '{id} · {agent} · {time}',
  deliveriesEmpty: '(no deliveries yet)',

  // Agent table
  agentsHeader: 'agent',
  tableState: 'state',
  tableTask: 'task',
  tableBranch: 'branch',
  tableSession: 'session',
  agentRunning: 'running',
  agentExited: 'exited',
  agentAbsent: 'no window',
  pmRunning: 'running',
  pmStarting: 'starting',
  pmAbsent: 'not running',
  pmForeign: 'another project holds it',
  pmUnknown: 'not a PM process',
  agentEmpty: '(no agents)',

  // Activity and recent actions
  activityHeading: 'activity (windows running in this session)',
  activitySource: 'source {path}',
  activityEmpty: '(no session activity)',
  recentHeading: 'recent actions',
  recentEmpty: '(no actions recorded yet)',

  // Pages and tabs
  pageOverview: 'overview',
  pageWork: 'work',
  pageMessages: 'messages & logs',
  pageBoard: 'board',
  pageTab: ' {name} ',
  pageTabActive: '▸{name}◂',

  // Board
  boardHeading: 'board',
  boardHeadingCount: 'board ({n})',
  boardCounts: '{todo} todo · {wip} wip · {review} review · {blocked} blocked · {done} done',
  boardDoneCollapsed: '… {n} older done/dropped rows folded',
  boardEmpty: '(board is empty)',
  kanbanEmptyLane: '·',
  laneHiddenAbove: '↑{n}',
  laneHiddenBelow: '↓{n}',

  // Detail view (read-only)
  detailTitle: 'detail {id}',
  detailNoFiles: '(no associated files for this entry)',
  detailTruncated: '… truncated (first 128 KiB shown)',
  detailLoading: '… loading',

  // Changes and specs
  changesHeading: 'active changes',
  changesHeadingCount: 'active changes ({n})',
  changeLine: '{done}/{total} · {phase}',
  changePhaseExplore: 'explore',
  changePhasePropose: 'propose',
  changePhaseApply: 'apply',
  changePhaseVerify: 'verify',
  changePhaseArchive: 'archive',
  specsHeading: 'specs',
  specsCount: '{specs} specs · {reqs} requirements',
  specsLine: '{name}  {n}',

  // Decisions
  decisionsHeading: 'recent decisions',
  decisionsCountSuffix: '{n} total',
  decisionsEmpty: '(no decisions recorded)',

  // Deferred queue
  queueHeading: 'deferred queue',
  queueHeadingCount: 'deferred queue {queued} (held {held})',
  queueLine: '{index}. [{state}] {name} · {age}',
  queueStateQueued: 'queued',
  queueStateHeld: 'held',
  queueHeldReason: 'held reason: {reason}',
  queueViewHint: 'Enter to view the full text',
  queueBackHint: 'Esc back to the list',
  queueEmpty: '(queue is empty)',
  queueFullHeading: 'full text: {name}',
  queueMeta: 'kind={kind} target={target} from={from}',

  // Inbox and threads
  inboxHeading: 'inbox and threads',
  inboxLine: 'inbox {inbox} · thread {thread} · {age}',
  inboxEmpty: '(no inbox/thread files)',

  // Patrol log and capacity trend
  patrolHeading: 'patrol log',
  patrolEmpty: '(no patrol records yet)',
  trendHeading: 'capacity trend',
  trendLine: 'RAM {mb} · swap {swap}',

  // Health
  healthHeading: 'health',
  healthLine: 'skill {version} · doctor {doctor} · last gates {gates}',
  healthDoctorOk: 'ok',
  healthDoctorWarn: 'warn',
  healthDoctorFail: 'fail',
  healthDoctorNA: 'unavailable',

  // Settings overlay
  settingsTitle: 'settings',
  settingsCursor: '›',
  prefLang: 'language',
  prefDefaultPage: 'default page',
  prefActivity: 'activity column',
  prefMouse: 'mouse',
  prefDensity: 'density',
  toggleOn: 'on',
  toggleOff: 'off',
  langNameZh: '中文',
  langNameEn: 'English',
  densityComfortable: 'comfortable',
  densityCompact: 'compact',
  settingsHint: '↑/↓ select · Enter toggle · Esc/, close',

  // Project-settings view (P22/B2)
  prefProjectSettings: 'Project settings',
  prefNavArrow: '›',
  settingsViewTitle: 'Project settings',
  settingsGroupApply: 'Takes effect now',
  settingsGroupRestart: 'Needs a restart',
  settingsGroupRefuse: 'Read-only',
  settingsGroupSeats: 'Seat models',
  settingsBadgeApply: 'apply',
  settingsBadgeRestart: 'restart',
  settingsBadgeRefuse: 'read-only',
  settingsUnknownBadge: 'unknown key',
  settingsUnset: 'unset · default {value}',
  settingsAuditHeading: 'Audit (newest)',
  settingsKeyHint: '↑/↓ rows · Enter edit · / filter · Esc back',
  keyFilter: '/ filter',
  settingFilterTitle: 'Filter settings',
  settingConfirm: 'Confirm: {key} {old} → {next} · {timing} (Enter again to write)',
  settingTimingApply: 'the next process that reads it',
  settingTimingRestart: 'needs a restart',
  settingDanger: 'Danger: {reason} (press Enter once more to confirm)',
  settingRejected: '✗ refused: {line}',
  settingWritten: '✓ wrote {key} = {value} · {timing}',
  settingRefused: '✗ read-only key: {line}',
  settingInvalid: '✗ invalid value: {line}',
  settingConflict: '! the contract changed under the editor (fingerprint mismatch) — nothing written; reloaded',
  settingWriteError: '✗ write failed (file unchanged): {line}',
  settingsRefusedRoute: 'read-only key: edit .pi/team/config.sh by hand',
  settingsSeatHint: 'seat model: team config set-agent-model {seat} <model>',
  seatPickerTitle: 'Pick the model for {seat}',
  seatPickerHint: '↑/↓ select · Enter edit that value · Esc back (a running window keeps its model until the next dispatch/resume)',
  seatPickerRemove: '- (remove the override, fall back to the default)',
  seatPickerFree: '… (free text provider/model)',
  settingSeatConfirm: 'Confirm seat {seat}: {old} → {next} · takes effect on the next dispatch/resume (a running window keeps its model) (Enter again to write)',
  settingSeatWritten: '✓ wrote seat {seat} = {value} · effective on the next dispatch/resume',
  settingSeatRemoved: '✓ removed the override of seat {seat} · back to the default {value}',
  keySeatPick: 'Enter select',
  seatSourceConfig: 'config',
  seatSourceExplicit: 'explicit',
  seatSourceRecord: 'stale record',
  seatOverride: 'override',
  seatFallback: 'fallback',

  // Global keys (footer)
  keyCompose: 'm compose',
  keyFlush: 'f flush',
  keyStandby: 's standby',
  keySettings: ', settings',
  keyPages: 'Tab/1-4 pages',
  keyScroll: '↑/↓ scroll',
  keyLanes: '←/→ lanes',
  keyCards: '↑/↓ cards',
  keyRows: '↑/↓ rows',
  keyOpen: 'Enter open',
  keyDetailClose: 'Esc/q back',
  keyDetailTabs: '←/→ file',
  keyDetailScroll: '↑/↓ scroll',
  keyQuit: 'q collapse',

  // Input line and receipts
  composeHint: 'Enter send · C-j newline · Esc cancel (draft kept) · C-o editor',
  composeHiddenAbove: '↑{n} rows',
  composeReasonHint: 'Enter standby · C-j newline (as a space) · Esc cancel',
  composeTitle: 'Message',
  composeStandbyTitle: 'Standby reason',
  receiptDelivered: '✓ delivered to the PM · delivered',
  receiptQueued: '… queued (the PM is typing) · queued',
  receiptHeld: '! held (copy under state/outbox/held/) · held',
  receiptError: '✗ delivery unconfirmed · {detail}',
  flushOk: '✓ flush · {detail}',
  flushFail: '✗ flush failed · {detail}',
  standbyOkOn: '✓ standby on (reason: {reason})',
  standbyOkOff: '✓ standby off',
  standbyFail: '✗ standby failed · {detail}',
  busySend: 'sending…',
  busyAction: 'working…',
  editorClosed: 'editor closed: draft {n} chars',
  noTeamCli: 'teamsmith CLI not found',
  sendUnconfirmed: 'delivery unconfirmed (no result token)',
  queuePending: 'the queue still holds entries',
}
