// English interface strings.
//
// Every rendered string comes from a table; see zh.ts for the contract. The English table is a
// translation, never a second source of truth: the key set, placeholders and value shapes are
// asserted equal to the Chinese table by `tests/panel-strings.mjs`.

/** @type {import('./types.js').Strings} */
export const en = {
  // Title band and status banner
  appTitle: 'teamsmith pulse',
  patrolLabel: 'patrol',
  patrolSeconds: 'patrol {n}s',
  standbyLabel: 'standby',
  standbyOn: 'standby on (reason: {reason})',
  standbyOff: 'standby off',
  standbyDash: 'standby —',
  pmLabel: 'PM',
  // M53: the consequence is part of {reason} (no registration → paste path; degraded watcher → slower, no loss).
  pmDeliveryWarning: 'delivery degraded: {reason}',
  pendingLabel: 'pending',
  pendingNone: 'none',
  outboxLabel: 'deferred',
  outboxHeldSuffix: ' (held {n})',
  capacityLabel: 'capacity',
  capacityRam: 'RAM {mb}',
  capacitySwap: 'swap {mb}',
  capacityAgents: '{n} more agents fit',
  dash: '—',

  // Project progress
  progressLabel: 'progress',
  progressTasks: 'tasks {parts}',
  taskTodo: 'todo',
  taskWip: 'wip',
  taskReview: 'review',
  taskBlocked: 'blocked',
  taskDone: 'done',
  taskDropped: 'dropped',
  progressChanges: 'changes {n}',
  progressSpecs: 'specs {specs} · {reqs} requirements',
  progressDecisions: 'decisions {n}',
  countPair: '{label} {n}',

  // Recent deliveries
  deliveriesLabel: 'recent deliveries',
  deliveryLine: '{id} · {agent} · {time}',
  deliveriesEmpty: '(no deliveries yet)',

  // Agent table
  agentsHeader: 'agent',
  tableState: 'state',
  tableTask: 'task',
  tableBranch: 'branch',
  tableSession: 'session',
  agentRunning: 'running',
  agentExited: 'exited',
  agentAbsent: 'no window',
  pmRunning: 'running',
  pmStarting: 'starting',
  pmAbsent: 'not running',
  pmForeign: 'another project holds it',
  pmUnknown: 'not a PM process',
  agentEmpty: '(no agents)',

  // Activity and recent actions
  activityHeading: 'activity (windows running in this session)',
  activitySource: 'source {path}',
  activityEmpty: '(no session activity)',
  recentHeading: 'recent actions',
  recentEmpty: '(no actions recorded yet)',

  // Pages and tabs
  pageOverview: 'overview',
  pageWork: 'work',
  pageMessages: 'messages & logs',
  pageBoard: 'board',
  pageTab: ' {name} ',
  pageTabActive: '▸{name}◂',

  // Board
  boardHeading: 'board',
  boardHeadingCount: 'board ({n})',
  boardCounts: '{todo} todo · {wip} wip · {review} review · {blocked} blocked · {done} done',
  boardDoneCollapsed: '… {n} older done/dropped rows folded',
  boardEmpty: '(board is empty)',
  kanbanEmptyLane: '·',
  laneHiddenAbove: '↑{n}',
  laneHiddenBelow: '↓{n}',

  // Detail view (read-only)
  detailTitle: 'detail {id}',
  detailNoFiles: '(no associated files for this entry)',
  detailTruncated: '… truncated (first 128 KiB shown)',
  detailLoading: '… loading',

  // Changes and specs
  changesHeading: 'active changes',
  changesHeadingCount: 'active changes ({n})',
  changeLine: '{done}/{total} · {phase}',
  changePhaseExplore: 'explore',
  changePhasePropose: 'propose',
  changePhaseApply: 'apply',
  changePhaseVerify: 'verify',
  changePhaseArchive: 'archive',
  specsHeading: 'specs',
  specsCount: '{specs} specs · {reqs} requirements',
  specsLine: '{name}  {n}',

  // Decisions
  decisionsHeading: 'recent decisions',
  decisionsCountSuffix: '{n} total',
  decisionsEmpty: '(no decisions recorded)',

  // Deferred queue
  queueHeading: 'deferred queue',
  queueHeadingCount: 'deferred queue {queued} (held {held})',
  queueLine: '{index}. [{state}] {name} · {age}',
  queueStateQueued: 'queued',
  queueStateHeld: 'held',
  queueHeldReason: 'held reason: {reason}',
  queueViewHint: 'Enter to view the full text',
  queueBackHint: 'Esc back to the list',
  queueEmpty: '(queue is empty)',
  queueFullHeading: 'full text: {name}',
  queueMeta: 'kind={kind} target={target} from={from}',

  // Inbox and threads
  inboxHeading: 'inbox and threads',
  inboxLine: 'inbox {inbox} · thread {thread} · {age}',
  inboxEmpty: '(no inbox/thread files)',

  // Patrol log and capacity trend
  patrolHeading: 'patrol log',
  patrolEmpty: '(no patrol records yet)',
  trendHeading: 'capacity trend',
  trendLine: 'RAM {mb} · swap {swap}',

  // Health
  healthHeading: 'health',
  healthLine: 'skill {version} · doctor {doctor} · last gates {gates}',
  healthDoctorOk: 'ok',
  healthDoctorWarn: 'warn',
  healthDoctorFail: 'fail',
  healthDoctorNA: 'unavailable',

  // Settings overlay
  settingsTitle: 'settings',
  settingsCursor: '›',
  prefLang: 'language',
  prefDefaultPage: 'default page',
  prefActivity: 'activity column',
  prefMouse: 'mouse',
  prefDensity: 'density',
  toggleOn: 'on',
  toggleOff: 'off',
  langNameZh: '中文',
  langNameEn: 'English',
  densityComfortable: 'comfortable',
  densityCompact: 'compact',
  settingsHint: '↑/↓ select · Enter toggle · Esc/, close',

  // Project-settings view (P22/B2)
  prefProjectSettings: 'Project settings',
  prefNavArrow: '›',
  settingsViewTitle: 'Project settings',
  settingsGroupApply: 'Takes effect now',
  settingsGroupRestart: 'Needs a restart',
  settingsGroupRefuse: 'Read-only',
  settingsGroupSeats: 'Seat models',
  settingsBadgeApply: 'apply',
  settingsBadgeRestart: 'restart',
  settingsBadgeRefuse: 'read-only',
  settingsUnknownBadge: 'unknown key',
  settingsUnset: 'unset · default {value}',
  settingsAuditHeading: 'Audit (newest)',
  settingsKeyHint: '↑/↓ rows · Enter edit · / filter · Esc back',
  keyFilter: '/ filter',
  settingFilterTitle: 'Filter settings',
  settingConfirm: 'Confirm: {key} {old} → {next} · {timing} (Enter again to write)',
  settingTimingApply: 'the next process that reads it',
  settingTimingRestart: 'needs a restart',
  settingDanger: 'Danger: {reason} (press Enter once more to confirm)',
  settingRejected: '✗ refused: {line}',
  settingWritten: '✓ wrote {key} = {value} · {timing}',
  settingRefused: '✗ read-only key: {line}',
  settingInvalid: '✗ invalid value: {line}',
  settingConflict: '! the contract changed under the editor (fingerprint mismatch) — nothing written; reloaded',
  settingWriteError: '✗ write failed (file unchanged): {line}',
  settingsRefusedRoute: 'read-only key: edit .pi/team/config.sh by hand',
  settingsSeatHint: 'seat model: team config set-agent-model {seat} <model>',
  settingsPairlistHint: 'seat models: team config set-agent-model <seat> <model|-> — this row’s editor is the seats block (Enter moves there; the pair list is never composed here)',
  settingsCliHint: 'CLI: team config set {key} <value>',
  settingsRefusedHint: 'read-only: edit {key} in .pi/team/config.sh by hand',
  settingsUnknownHint: 'unknown key: {key} is in the file but not in the command schema',
  settingsChoiceTitle: 'Choose a value for {label} · {key}',
  settingsChoiceHint: '↑/↓ choose · Enter edit that value · Esc back (two more Enters inside the editor do the write)',
  settingsChoiceCurrent: 'current',
  settingsChoiceDefault: 'default',
  settingsChoiceKeepUnset: 'keep unset (cancel writes nothing and leaves no audit line)',
  settingsChoiceClear: 'clear (write the empty value)',
  settingsChoiceFree: '… (free text)',
  settingsChoiceInterval: 'accepted interval {min}–{max} (empty = unbounded)',
  settingsChoiceNoChoice: 'the kind {kind} has no choice set; the command still validates the write (Enter opens free text)',
  settingsChoicePairlist: 'The seats block is this row’s editor (command: team config set-agent-model <seat> <model|->)',
  settingsBoolOn: 'on (1)',
  settingsBoolOff: 'off (0)',
  settingsPathExists: 'exists',
  settingsPathMissing: 'missing',
  settingsPathNotExec: 'not executable',
  seatPickerTitle: 'Pick the model for {seat}',
  seatPickerHint: '↑/↓ select · Enter edit that value · Esc back (a running window keeps its model until the next dispatch/resume)',
  seatPickerRemove: '- (remove the override, fall back to the default)',
  seatPickerFree: '… (free text provider/model)',
  settingSeatConfirm: 'Confirm seat {seat}: {old} → {next} · takes effect on the next dispatch/resume (a running window keeps its model) (Enter again to write)',
  settingSeatWritten: '✓ wrote seat {seat} = {value} · effective on the next dispatch/resume',
  settingSeatRemoved: '✓ removed the override of seat {seat} · back to the default {value}',
  keySeatPick: 'Enter select',
  seatSourceConfig: 'config',
  seatSourceExplicit: 'explicit',
  seatSourceRecord: 'stale record',
  seatOverride: 'override',
  seatFallback: 'fallback',

  // The human labels of the contract keys (M49): one per key of `lib/cmd-config.sh`'s schema, and
  // the row's main text — the bare TEAM_* stays where it aligns with the CLI (the editor's title,
  // the confirmation line, the view's command hint). A key the schema does not know has no label
  // and falls back to its raw name (`keyLabel()`). Completeness is asserted by
  // tests/panel-strings.mjs (schema ↔ both tables, both directions). Order follows the schema.
  // -- identity and ledger layout (read-only)
  label_TEAM_PROJECT: 'Project name',
  label_TEAM_SESSION: 'Session name',
  label_TEAM_PM_WINDOW: 'PM window',
  label_TEAM_AGENTS: 'Roster',
  label_TEAM_DOCS_DIR: 'Ledger dir',
  label_TEAM_WORKTREES_DIR: 'Worktree dir',
  label_TEAM_STATE_DIR: 'State dir',
  label_TEAM_MEETINGS_DIR: 'Meeting dir',
  label_TEAM_SPEC_DIR: 'Spec dir',
  label_TEAM_ROOT: 'Project root',
  label_TEAM_MAIN_ROOT: 'Main checkout root',
  label_TEAM_CONFIG_FILE: 'Contract file',
  // -- branch and forge (read-only)
  label_TEAM_BRANCH_MODE: 'Branch naming mode',
  label_TEAM_TASK_BRANCH_PREFIX: 'Task branch prefix',
  label_TEAM_AGENT_BRANCH_PREFIX: 'Seat branch prefix',
  label_TEAM_PROTECTED_BRANCH: 'Protected branch',
  label_TEAM_REMOTE: 'Remote',
  label_TEAM_VCS: 'Forge',
  label_TEAM_TOKEN_FILE: 'Token file',
  label_TEAM_GITLAB_HOST: 'GitLab host',
  label_TEAM_GITLAB_PROJECT: 'GitLab project',
  label_TEAM_GITLAB_TOKEN_FILE: 'GitLab token file',
  label_TEAM_MERGE_PREFER_THEIRS: 'Prefer branch side',
  // -- permissions and dependencies (read-only)
  label_TEAM_CONFIRM_WRITES: 'Confirm writes',
  label_TEAM_ALLOW_FOREIGN_IDENTITY: 'Allow foreign ID',
  label_TEAM_ALLOW_FOREIGN_SESSION: 'Allow foreign window',
  label_TEAM_GUARD_FOREIGN_TARGET: 'Guard foreign targets',
  label_TEAM_REPLACE_FOREIGN_PM: 'Replace foreign PM',
  label_TEAM_ALLOW_DESTRUCTIVE_TMUX: 'Allow destructive ops',
  label_TEAM_ASSUME_YES: 'Assume yes',
  label_TEAM_REQUIRE_JS: 'Require JS runtime',
  label_TEAM_REQUIRE_OPENSPEC: 'Require OpenSpec',
  label_TEAM_REQUIRE_MAGIC_CONTEXT: 'Require Magic Context',
  label_TEAM_PI_AGENT_DIR: 'Pi agent dir',
  label_TEAM_PI_SETTINGS_FILE: 'Pi settings file',
  label_TEAM_MEMINFO_FILE: 'meminfo file',
  label_TEAM_SMOKE_FAST: 'Smoke fast mode',
  // -- roster, model resolution and adapters
  label_TEAM_MODEL_LIMITS: 'Concurrency limits',
  label_TEAM_MODEL_WINDOWS: 'Context windows',
  label_TEAM_SESSION_WARN_TOKENS: 'Context warn tokens',
  label_TEAM_EXTRA_PI_ARGS: 'Seat extra args',
  label_TEAM_AGENT_CMD: 'Seat launch command',
  label_TEAM_AGENT_NOTIFY_CMD: 'Turn-end notify cmd',
  label_TEAM_AGENT_LOG_GLOB: 'Seat log glob',
  label_TEAM_PI_BIN: 'pi binary',
  label_TEAM_AGENT_BIN: 'Seat binary',
  label_TEAM_OPENSPEC_BIN: 'openspec binary',
  label_TEAM_JS_BIN: 'JS runtime',
  // -- per-seat models (needs a restart)
  label_TEAM_DEFAULT_MODEL: 'Default model',
  label_TEAM_AGENT_MODELS: 'Per-seat models',
  label_TEAM_PM_MODEL: 'PM model',
  // -- workflow and gates
  label_TEAM_GATES: 'Gate commands',
  label_TEAM_INSTALL_CMD: 'Install command',
  label_TEAM_TASK_BRANCH_RESET: 'Reset task branch',
  label_TEAM_DISPATCH_VERIFY_SEC: 'Dispatch check wait',
  label_TEAM_DISPATCH_ALIVE_SEC: 'Alive check wait',
  label_TEAM_SQUASH_LOOKBACK: 'Squash look-back',
  label_TEAM_REVIEW_TIMEOUT: 'Review timeout',
  label_TEAM_REVIEW_TIMEOUT_GRACE: 'Timeout grace',
  label_TEAM_REVIEW_ALLOW_DIRTY: 'Allow dirty checkout',
  label_TEAM_REVIEW_ALLOW_IGNORED: 'Allow ignored files',
  label_TEAM_REVIEW_ALLOW_UNRESOLVED_BRANCH: 'Allow unresolved tip',
  label_TEAM_REVIEW_ANY_DIR: 'Skip checkout guard',
  label_TEAM_BOARD_DONE_FORCE: 'Force board done',
  label_TEAM_BOARD_DONE_REASON: 'Force-done reason',
  // -- capacity and delivery
  label_TEAM_MIN_FREE_SWAP_MB: 'Free swap floor',
  label_TEAM_MIN_TOTAL_MB: 'RAM+swap floor',
  label_TEAM_MIN_AVAIL_MB: 'Free memory floor',
  label_TEAM_WARN_AVAIL_MB: 'Memory warn line',
  label_TEAM_ZRAM_WARN_PCT: 'zram warn percent',
  label_TEAM_AGENT_MEM_MB: 'Seat memory cap',
  label_TEAM_NOTIFY_TMUX: 'tmux delivery',
  label_TEAM_NOTIFY_DEDUP_SEC: 'Notify dedup window',
  label_TEAM_INBOX_MAX_CHARS: 'Inbox summary chars',
  label_TEAM_NOTIFY_LOG: 'Notify debug log',
  label_TEAM_DEFER_TTL: 'Queued delivery TTL',
  label_TEAM_OUTBOX_MAX: 'Outbox cap',
  label_TEAM_PANEL_DETAIL_CAP: 'Detail read cap',
  // -- pulse and panel (needs a restart)
  label_TEAM_PULSE_INTERVAL: 'Patrol interval',
  label_TEAM_MONITOR_REFRESH: 'Panel refresh period',
  label_TEAM_MONITOR_EVENTS: 'Initial event rows',
  label_TEAM_MONITOR_UI: 'Panel renderer',
  label_TEAM_MONITOR_ACTIVITY: 'Activity column',
  label_TEAM_AGENT_LOG_TAIL_BYTES: 'Log tail read cap',
  label_TEAM_PULSE_WINDOW: 'Pulse window name',
  // -- patrol policy
  label_TEAM_PULSE_NUDGE_GAP: 'Nudge gap',
  label_TEAM_PULSE_PENDING_BOARD: 'Wake on board to-do',
  label_TEAM_PULSE_REBUILD_TMUX: 'Rebuild tmux server',
  label_TEAM_PULSE_MAX_RESTARTS: 'Max auto-restarts',
  // -- PM lifecycle (needs a restart)
  label_TEAM_PM_SESSION_ID: 'PM session id',
  label_TEAM_PM_CMD: 'PM launch command',
  label_TEAM_PM_BIN: 'PM binary',
  label_TEAM_PM_EXTRA_PI_ARGS: 'PM extra args',
  label_TEAM_PM_RESUME_ARGS: 'PM resume args',
  label_TEAM_PM_START_WAIT: 'PM start wait',
  // -- live sessions (needs a restart)
  label_TEAM_INBOX_WATCH_MAX_BYTES: 'Watcher read cap',
  label_TEAM_INBOX_WATCH_PREVIEW: 'Preview lines',
  label_TEAM_INBOX_WATCH_REPLAY_MAX: 'Replay cap',
  label_TEAM_INBOX_WATCH_SEEN_MAX: 'Seen-record cap',
  label_TEAM_INBOX_WATCH_STALE: 'Stale threshold',
  label_TEAM_INBOX_WATCH_POLL_MS: 'Poll interval',
  label_TEAM_INBOX_WATCH_HEARTBEAT_MS: 'Heartbeat interval',
  label_TEAM_INBOX_WATCH_TARGET: 'Delivery target',
  label_TEAM_BG_LOG_MAX_BYTES: 'Background log cap',
  // -- cross-project meetings
  label_TEAM_MEETING_TTL_HOURS: 'Meeting TTL',
  label_TEAM_MEETING_MAX_TURNS: 'Meeting turn cap',
  label_TEAM_MEETING_KNOCK: 'Allow knocking',
  label_TEAM_MEETING_ALLOW_USER_ID: 'Users who may knock',

  // Global keys (footer)
  keyCompose: 'm compose',
  keyFlush: 'f flush',
  keyStandby: 's standby',
  keySettings: ', settings',
  keyPages: 'Tab/1-4 pages',
  keyScroll: '↑/↓ scroll',
  keyLanes: '←/→ lanes',
  keyCards: '↑/↓ cards',
  keyRows: '↑/↓ rows',
  keyOpen: 'Enter open',
  keyDetailClose: 'Esc/q back',
  keyDetailTabs: '←/→ file',
  keyDetailScroll: '↑/↓ scroll',
  keyQuit: 'q collapse',

  // Input line and receipts
  composeHint: 'Enter send · C-j newline · Esc cancel (draft kept) · C-o editor',
  composeHiddenAbove: '↑{n} rows',
  composeReasonHint: 'Enter standby · C-j newline (as a space) · Esc cancel',
  composeTitle: 'Message',
  composeStandbyTitle: 'Standby reason',
  receiptDelivered: '✓ delivered to the PM · delivered',
  receiptQueued: '… queued (the PM is typing) · queued',
  receiptHeld: '! held (copy under state/outbox/held/) · held',
  receiptError: '✗ delivery unconfirmed · {detail}',
  flushOk: '✓ flush · {detail}',
  flushFail: '✗ flush failed · {detail}',
  standbyOkOn: '✓ standby on (reason: {reason})',
  standbyOkOff: '✓ standby off',
  standbyFail: '✗ standby failed · {detail}',
  busySend: 'sending…',
  busyAction: 'working…',
  editorClosed: 'editor closed: draft {n} chars',
  noTeamCli: 'teamsmith CLI not found',
  sendUnconfirmed: 'delivery unconfirmed (no result token)',
  queuePending: 'the queue still holds entries',
}
