// 中文界面字符串表（默认语言）。
//
// 所有上屏文本都必须从这里取：`tests/panel-strings.mjs` 会断言两张表的键集合、占位符集合与
// 非空值完全一致，并扫描 `src/**`（strings/ 除外）确保没有残留的中文正文。
// 本文件是纯 ESM（只有注释与 JSDoc），断言脚本会把它复制成 .mjs 用任意 JS 运行时导入。

/** @type {import('./types.js').Strings} */
export const zh = {
  // 标题与状态横幅
  appTitle: 'teamsmith pulse',
  patrolLabel: '巡检',
  patrolSeconds: '巡检 {n}s',
  standbyLabel: '待命',
  standbyOn: '待命 on（原因：{reason}）',
  standbyOff: '待命 off',
  standbyDash: '待命 —',
  pmLabel: 'PM',
  pmDeliveryWarning: '投递降级：{reason} → 通知退回输入框粘贴慢路径（重启进程才加载扩展）',
  pendingLabel: '待办',
  pendingNone: '无',
  outboxLabel: '延后投递',
  outboxHeldSuffix: '（扣住 {n}）',
  capacityLabel: '容量',
  capacityRam: 'RAM {mb}',
  capacitySwap: 'swap {mb}',
  capacityAgents: '可再加 {n} 个 agent',
  dash: '—',

  // 项目进度
  progressLabel: '项目进度',
  progressTasks: '任务 {parts}',
  taskTodo: '待办',
  taskWip: '进行',
  taskReview: '待复验',
  taskBlocked: '阻塞',
  taskDone: '完成',
  taskDropped: '已放弃',
  progressChanges: '变更 {n}',
  progressSpecs: '规格 {specs} 项 · {reqs} 条需求',
  progressDecisions: '决策 {n}',
  countPair: '{label} {n}',

  // 最近交付
  deliveriesLabel: '最近交付',
  deliveryLine: '{id} · {agent} · {time}',
  deliveriesEmpty: '（还没有交付记录）',

  // agent 表
  agentsHeader: '代理',
  tableState: '状态',
  tableTask: '任务',
  tableBranch: '分支',
  tableSession: '会话',
  agentRunning: '在跑',
  agentExited: '已退出',
  agentAbsent: '无窗口',
  pmRunning: '在运行',
  pmStarting: '正在启动',
  pmAbsent: '未在跑',
  pmForeign: '别的项目占着',
  pmUnknown: '非 PM 进程',
  agentEmpty: '（没有 agent）',

  // 活动与最近动作
  activityHeading: '活动（仅本 session 在跑的窗口）',
  activitySource: '源 {path}',
  activityEmpty: '（没有会话活动）',
  recentHeading: '最近动作',
  recentEmpty: '（还没有动作记录）',

  // 页面与页签
  pageOverview: '总览',
  pageWork: '工作',
  pageMessages: '消息与日志',
  pageBoard: '看板',
  pageTab: ' {name} ',
  pageTabActive: '▸{name}◂',

  // 看板
  boardHeading: '任务看板',
  boardHeadingCount: '任务看板 ({n})',
  boardCounts: '{todo} 待办 · {wip} 进行 · {review} 待复验 · {blocked} 阻塞 · {done} 完成',
  boardDoneCollapsed: '… 其余 {n} 条 done/dropped 收起',
  boardEmpty: '（看板为空）',
  kanbanEmptyLane: '·',
  laneHiddenAbove: '↑{n}',
  laneHiddenBelow: '↓{n}',

  // 详情视图（只读）
  detailTitle: '详情 {id}',
  detailNoFiles: '（这个入口没有关联文件）',
  detailTruncated: '… 已截断（只显示前 128 KiB）',
  detailLoading: '… 读取中',

  // 变更与规格
  changesHeading: '活动变更',
  changesHeadingCount: '活动变更 ({n})',
  changeLine: '{done}/{total} · {phase}',
  changePhaseExplore: '探索',
  changePhasePropose: '提案',
  changePhaseApply: '实施',
  changePhaseVerify: '验证',
  changePhaseArchive: '归档',
  specsHeading: '规格',
  specsCount: '{specs} 项 · {reqs} 条需求',
  specsLine: '{name}  {n}',

  // 决策
  decisionsHeading: '最近决策',
  decisionsCountSuffix: '共 {n} 条',
  decisionsEmpty: '（没有决策记录）',

  // 延后队列
  queueHeading: '延后队列',
  queueHeadingCount: '延后队列 {queued}（扣住 {held}）',
  queueLine: '{index}. [{state}] {name} · {age}',
  queueStateQueued: '排队',
  queueStateHeld: '滞留',
  queueHeldReason: '扣住原因：{reason}',
  queueViewHint: 'Enter 看全文',
  queueBackHint: 'Esc 返回列表',
  queueEmpty: '（队列为空）',
  queueFullHeading: '条目全文：{name}',
  queueMeta: 'kind={kind} target={target} from={from}',

  // 收件箱与往来记录（P20/B6：docs/team/threads/ 的中文名只叫 往来）
  inboxHeading: '收件箱与往来',
  inboxLine: '收件箱 {inbox} 条 · 往来 {thread} 条 · {age}',
  inboxEmpty: '（没有收件箱/往来记录）',

  // 巡检日志与容量趋势
  patrolHeading: '巡检日志',
  patrolEmpty: '（还没有巡检记录）',
  trendHeading: '容量趋势',
  trendLine: 'RAM {mb} · swap {swap}',

  // 健康
  healthHeading: '健康',
  healthLine: '技能 {version} · doctor {doctor} · 上次门禁 {gates}',
  healthDoctorOk: 'ok',
  healthDoctorWarn: 'warn',
  healthDoctorFail: 'fail',
  healthDoctorNA: '不可用',

  // 设置浮层
  settingsTitle: '设置',
  settingsCursor: '›',
  prefLang: '语言',
  prefDefaultPage: '默认页面',
  prefActivity: '活动列',
  prefMouse: '鼠标',
  prefDensity: '密度',
  toggleOn: '开',
  toggleOff: '关',
  langNameZh: '中文',
  langNameEn: 'English',
  densityComfortable: '舒适',
  densityCompact: '紧凑',
  settingsHint: '↑/↓ 选择 · Enter 切换 · Esc/, 关闭',

  // 项目设置视图（P22/B2）
  prefProjectSettings: '项目设置',
  prefNavArrow: '›',
  settingsViewTitle: '项目设置',
  settingsGroupApply: '立即生效',
  settingsGroupRestart: '需要重启',
  settingsGroupRefuse: '只读',
  settingsGroupSeats: '按席位模型',
  settingsBadgeApply: '立即生效',
  settingsBadgeRestart: '需重启',
  settingsBadgeRefuse: '只读',
  settingsUnknownBadge: '未知键',
  settingsUnset: '未设 · 默认 {value}',
  settingsAuditHeading: '审计（最近）',
  settingsKeyHint: '↑/↓ 行 · Enter 编辑 · / 筛选 · Esc 返回',
  keyFilter: '/ 筛选',
  settingFilterTitle: '筛选设置',
  settingConfirm: '确认：{key} {old} → {next} · {timing}（再按 Enter 写入）',
  settingTimingApply: '下一个读取它的进程生效',
  settingTimingRestart: '需要重启才生效',
  settingDanger: '危险：{reason}（再按一次 Enter 确认）',
  settingRejected: '✗ 被拒：{line}',
  settingWritten: '✓ 已写入 {key} = {value} · {timing}',
  settingRefused: '✗ 只读键：{line}',
  settingInvalid: '✗ 值不合法：{line}',
  settingConflict: '! 契约在编辑器打开后变过（指纹不符）—— 什么都没写；已重读',
  settingWriteError: '✗ 写入失败（原文件未动）：{line}',
  settingsRefusedRoute: '只读键：手改 .pi/team/config.sh',
  settingsSeatHint: '席位模型：team config set-agent-model {seat} <model>',
  settingsCliHint: '命令行：team config set {key} <新值>',
  settingsRefusedHint: '只读：手改 .pi/team/config.sh 里的 {key}',
  settingsUnknownHint: '未知键：{key} 在文件里，命令的 schema 不认识',
  seatPickerTitle: '选择 {seat} 的模型',
  seatPickerHint: '↑/↓ 选择 · Enter 编辑该值 · Esc 返回（运行中的窗口保持旧模型，下次 dispatch/resume 才换）',
  seatPickerRemove: '-（移除覆盖，回退默认）',
  seatPickerFree: '…（自由输入 provider/model）',
  settingSeatConfirm: '确认席位 {seat}：{old} → {next} · 下次 dispatch/resume 生效（运行中的窗口保持旧模型）（再按 Enter 写入）',
  settingSeatWritten: '✓ 已写入席位 {seat} = {value} · 下次 dispatch/resume 生效',
  settingSeatRemoved: '✓ 已移除席位 {seat} 的覆盖 · 回到默认 {value}',
  keySeatPick: 'Enter 选择',
  seatSourceConfig: '配置',
  seatSourceExplicit: '显式',
  seatSourceRecord: '历史记录',
  seatOverride: '覆盖',
  seatFallback: '回退默认',

  // 契约键的人话标签（M49）：`lib/cmd-config.sh` 的 schema 每个键一条，行的主文本用它，
  // 裸 TEAM_* 只留在与 CLI 对齐的地方（编辑器标题、确认行、视图底部的命令行提示）。
  // schema 不认识的键没有标签 → 回退显示原始键（`keyLabel()`）。完整性由
  // tests/panel-strings.mjs 断言（schema ↔ 两张表，两个方向都查）。顺序与 schema 一致。
  // —— 身份与账本布局（只读）
  label_TEAM_PROJECT: '项目名',
  label_TEAM_SESSION: '会话名',
  label_TEAM_PM_WINDOW: 'PM 窗口',
  label_TEAM_AGENTS: '名册',
  label_TEAM_DOCS_DIR: '账本目录',
  label_TEAM_WORKTREES_DIR: '工作树目录',
  label_TEAM_STATE_DIR: '状态目录',
  label_TEAM_MEETINGS_DIR: '会议目录',
  label_TEAM_SPEC_DIR: '规格目录',
  label_TEAM_ROOT: '项目根',
  label_TEAM_MAIN_ROOT: '主检出根',
  label_TEAM_CONFIG_FILE: '契约文件',
  // —— 分支与托管平台（只读）
  label_TEAM_BRANCH_MODE: '分支命名模式',
  label_TEAM_TASK_BRANCH_PREFIX: '任务分支前缀',
  label_TEAM_AGENT_BRANCH_PREFIX: '席位分支前缀',
  label_TEAM_PROTECTED_BRANCH: '保护分支',
  label_TEAM_REMOTE: '远端',
  label_TEAM_VCS: '托管平台',
  label_TEAM_TOKEN_FILE: '凭据文件',
  label_TEAM_GITLAB_HOST: 'GitLab 主机',
  label_TEAM_GITLAB_PROJECT: 'GitLab 项目',
  label_TEAM_GITLAB_TOKEN_FILE: 'GitLab 凭据文件',
  label_TEAM_MERGE_PREFER_THEIRS: '冲突默认取分支侧',
  // —— 权限与依赖策略（只读）
  label_TEAM_CONFIRM_WRITES: '写入前确认',
  label_TEAM_ALLOW_FOREIGN_IDENTITY: '放行外部身份',
  label_TEAM_ALLOW_FOREIGN_SESSION: '放行外部会话',
  label_TEAM_GUARD_FOREIGN_TARGET: '拦截外部目标',
  label_TEAM_REPLACE_FOREIGN_PM: '可替换外部 PM',
  label_TEAM_ALLOW_DESTRUCTIVE_TMUX: '放行破坏性操作',
  label_TEAM_ASSUME_YES: '默认全部确认',
  label_TEAM_REQUIRE_JS: '必需 JS 运行时',
  label_TEAM_REQUIRE_OPENSPEC: '必需 OpenSpec',
  label_TEAM_REQUIRE_MAGIC_CONTEXT: '必需 Magic Context',
  label_TEAM_PI_AGENT_DIR: 'Pi 配置目录',
  label_TEAM_PI_SETTINGS_FILE: 'Pi 设置文件',
  label_TEAM_MEMINFO_FILE: '内存信息文件',
  label_TEAM_SMOKE_FAST: '冒烟快模式',
  // —— 名册、模型解析与适配器
  label_TEAM_MODEL_LIMITS: '模型并发上限',
  label_TEAM_MODEL_WINDOWS: '显式上下文窗口',
  label_TEAM_SESSION_WARN_TOKENS: '上下文告警阈值',
  label_TEAM_EXTRA_PI_ARGS: '席位附加参数',
  label_TEAM_AGENT_CMD: '席位启动命令',
  label_TEAM_AGENT_NOTIFY_CMD: '收工通知命令',
  label_TEAM_AGENT_LOG_GLOB: '席位日志路径',
  label_TEAM_PI_BIN: 'pi 可执行文件',
  label_TEAM_AGENT_BIN: '席位可执行文件',
  label_TEAM_OPENSPEC_BIN: 'openspec 可执行文件',
  label_TEAM_JS_BIN: 'JS 运行时',
  // —— 按席位模型（需重启）
  label_TEAM_DEFAULT_MODEL: '默认模型',
  label_TEAM_AGENT_MODELS: '按席位模型',
  label_TEAM_PM_MODEL: 'PM 模型',
  // —— 工作流与门禁
  label_TEAM_GATES: '门禁命令',
  label_TEAM_INSTALL_CMD: '安装命令',
  label_TEAM_TASK_BRANCH_RESET: '派单时重置分支',
  label_TEAM_DISPATCH_VERIFY_SEC: '派单检查等待',
  label_TEAM_DISPATCH_ALIVE_SEC: '存活判定等待',
  label_TEAM_SQUASH_LOOKBACK: 'squash 回看条数',
  label_TEAM_REVIEW_TIMEOUT: '复验超时',
  label_TEAM_REVIEW_TIMEOUT_GRACE: '超时宽限',
  label_TEAM_REVIEW_ALLOW_DIRTY: '复验放行脏工作树',
  label_TEAM_REVIEW_ALLOW_IGNORED: '复验放行忽略文件',
  label_TEAM_REVIEW_ALLOW_UNRESOLVED_BRANCH: '放行未解析分支',
  label_TEAM_REVIEW_ANY_DIR: '复验跳过目录校验',
  label_TEAM_BOARD_DONE_FORCE: '强制标记 done',
  label_TEAM_BOARD_DONE_REASON: '强制放行理由',
  // —— 容量与投递
  label_TEAM_MIN_FREE_SWAP_MB: 'swap 底线',
  label_TEAM_MIN_TOTAL_MB: '内存硬底线',
  label_TEAM_MIN_AVAIL_MB: '可用内存底线',
  label_TEAM_WARN_AVAIL_MB: '可用内存告警线',
  label_TEAM_ZRAM_WARN_PCT: 'zram 告警比例',
  label_TEAM_AGENT_MEM_MB: '席位内存上限',
  label_TEAM_NOTIFY_TMUX: '走 tmux 投递',
  label_TEAM_NOTIFY_DEDUP_SEC: '通知去重窗口',
  label_TEAM_INBOX_MAX_CHARS: '收件箱摘要字数',
  label_TEAM_NOTIFY_LOG: '通知调试日志',
  label_TEAM_DEFER_TTL: '排队过期时间',
  label_TEAM_OUTBOX_MAX: '发件箱条数上限',
  label_TEAM_PANEL_DETAIL_CAP: '详情文件读取上限',
  // —— 巡检与面板（需重启）
  label_TEAM_PULSE_INTERVAL: '巡检周期',
  label_TEAM_MONITOR_REFRESH: '面板刷新周期',
  label_TEAM_MONITOR_EVENTS: '事件初始条数',
  label_TEAM_MONITOR_UI: '面板渲染器',
  label_TEAM_MONITOR_ACTIVITY: '活动列',
  label_TEAM_AGENT_LOG_TAIL_BYTES: '日志尾部读取上限',
  label_TEAM_PULSE_WINDOW: '巡检窗口名',
  // —— 巡检策略
  label_TEAM_PULSE_NUDGE_GAP: '重复提醒间隔',
  label_TEAM_PULSE_PENDING_BOARD: '看板待办也唤醒',
  label_TEAM_PULSE_REBUILD_TMUX: '自愈重建 server',
  label_TEAM_PULSE_MAX_RESTARTS: '自动拉起次数上限',
  // —— PM 生命周期（需重启）
  label_TEAM_PM_SESSION_ID: 'PM 会话 ID',
  label_TEAM_PM_CMD: 'PM 启动命令',
  label_TEAM_PM_BIN: 'PM 可执行文件',
  label_TEAM_PM_EXTRA_PI_ARGS: 'PM 附加参数',
  label_TEAM_PM_RESUME_ARGS: 'PM 续跑参数',
  label_TEAM_PM_START_WAIT: 'PM 启动等待',
  // —— 活着的会话（需重启）
  label_TEAM_INBOX_WATCH_MAX_BYTES: 'watcher 读取上限',
  label_TEAM_INBOX_WATCH_PREVIEW: '预览行数',
  label_TEAM_INBOX_WATCH_REPLAY_MAX: '重放条数上限',
  label_TEAM_INBOX_WATCH_SEEN_MAX: '已见记录上限',
  label_TEAM_INBOX_WATCH_STALE: '过期判定秒数',
  label_TEAM_INBOX_WATCH_POLL_MS: '轮询间隔',
  label_TEAM_INBOX_WATCH_HEARTBEAT_MS: '心跳间隔',
  label_TEAM_INBOX_WATCH_TARGET: '投递目标',
  label_TEAM_BG_LOG_MAX_BYTES: '后台日志上限',
  // —— 跨项目会议
  label_TEAM_MEETING_TTL_HOURS: '会议有效期',
  label_TEAM_MEETING_MAX_TURNS: '会议轮次上限',
  label_TEAM_MEETING_KNOCK: '允许敲门',
  label_TEAM_MEETING_ALLOW_USER_ID: '可敲门用户',

  // 全局键位（页脚）
  keyCompose: 'm 写信',
  keyFlush: 'f 冲刷',
  keyStandby: 's 待命',
  keySettings: ', 设置',
  keyPages: 'Tab/1-4 翻页',
  keyScroll: '↑/↓ 滚动',
  keyLanes: '←/→ 车道',
  keyCards: '↑/↓ 卡片',
  keyRows: '↑/↓ 行',
  keyOpen: 'Enter 打开',
  keyDetailClose: 'Esc/q 返回',
  keyDetailTabs: '←/→ 文件',
  keyDetailScroll: '↑/↓ 滚动',
  keyQuit: 'q 收起',

  // 输入行与回执
  composeHint: 'Enter 发送 · C-j 换行 · Esc 取消（保留草稿）· C-o 编辑器',
  composeHiddenAbove: '↑{n} 行',
  composeReasonHint: 'Enter 进入待命 · C-j 换行（变空格）· Esc 取消',
  composeTitle: '写信',
  composeStandbyTitle: '待命原因',
  receiptDelivered: '✓ 已送达 PM · delivered',
  receiptQueued: '… 已入队（PM 的输入框在忙）· queued',
  receiptHeld: '! 滞留（副本在 state/outbox/held/）· held',
  receiptError: '✗ 投递未确认 · {detail}',
  flushOk: '✓ 冲刷 · {detail}',
  flushFail: '✗ 冲刷失败 · {detail}',
  standbyOkOn: '✓ 待命 on（原因：{reason}）',
  standbyOkOff: '✓ 待命 off',
  standbyFail: '✗ 待命失败 · {detail}',
  busySend: '发送中…',
  busyAction: '执行中…',
  editorClosed: '编辑器已关闭：草稿 {n} 字符',
  noTeamCli: '找不到 teamsmith CLI',
  sendUnconfirmed: '投递未确认（没有拿到结果码）',
  queuePending: '队列仍有条目未投递',
}
